apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/abalage/home-assistant-k8s/base?ref=main

patchesJson6902:
- target:
    version: v1
    kind: Ingress
    name: home-assistant
  patch: |-
    - op: replace
      path: /spec/ingressClassName
      value: nginx

images:
- name: ghcr.io/home-assistant/home-assistant
  newTag: 2022.12.1
